
version: 0.1.{build}
branches:
  only:
  - main
image: Visual Studio 2019
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: source/CachedImage.sln
  publish_wap: true
  publish_azure: true
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: detailed
deploy:
- provider: NuGet
  api_key:
    secure: smwcM4a1NxsychOWxaIlkluQRkbCJLHqxhfuNNNI+X2wuyIK6zFbN54OUdiOXJtU
  artifact: /.*\.nupkg/
  on:
    branch: main
